storage:
  dbPath: "/var/mongodb/db"
net:
  bindIp : "127.0.0.1,192.168.103.100"
  port: 27000
security:
  authorization: "enabled"
systemLog:
  destination: file
  path: /var/mongodb/db/mongod.log
  logAppend: true
processManagement:
  fork: true
operationProfiling:
  slowOpThresholdMs: 50